# Generated by Django 5.2.8 on 2025-11-30 14:45

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the broker (e.g., Zerodha, Groww)', max_length=100)),
                ('broker_user_id', models.CharField(blank=True, help_text='User ID/Client ID with the broker (alphanumeric)', max_length=50, null=True)),
                ('demat_account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Demat account number (encrypted)', null=True)),
                ('demat_account_number_last4', models.CharField(blank=True, editable=False, help_text='Last 4 digits of demat account number', max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of the broker account', on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'brokers',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset (e.g., Apple Inc., Vanguard 500)', max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='Ticker symbol (optional, e.g., AAPL)', max_length=20, null=True)),
                ('investment_type', models.CharField(choices=[('stock', 'Stock'), ('mutual_fund', 'Mutual Fund'), ('etf', 'ETF'), ('gold', 'Gold'), ('reit', 'REIT'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], default='stock', help_text='Type of investment asset', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, help_text='Current market price per unit (manually updated)', max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Investment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='Broker where this investment is held', on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.broker')),
                ('user', models.ForeignKey(help_text='Owner of the investment', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='Type of transaction', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of transaction')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of units bought/sold', max_digits=18)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at time of transaction', max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Brokerage, taxes, and other fees', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total value of transaction (calculated)', max_digits=18)),
                ('notes', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(help_text='The investment asset being transacted', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Investment Transaction',
                'verbose_name_plural': 'Investment Transactions',
                'db_table': 'investment_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='idx_inv_user_status'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['broker'], name='idx_inv_broker'),
        ),
    ]
