# Generated by Django 5.2.8 on 2025-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Broker account status', max_length=20),
        ),
    ]
