# Generated by Django 5.2.8 on 2025-12-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_broker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Number of units bought/sold', max_digits=18),
        ),
    ]
