# Generated by Django 5.2.8 on 2025-11-24 15:37

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name/nickname for the account', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial balance when account was opened', max_digits=18)),
                ('currency', models.CharField(default='INR', help_text='Currency code (fixed to INR for V1)', max_length=3)),
                ('opened_on', models.DateField(blank=True, help_text='Date when account was opened', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Account status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the account', null=True)),
                ('picture', models.ImageField(blank=True, help_text='Account picture/icon (optional)', null=True, upload_to='account_pictures/')),
                ('color', models.CharField(blank=True, help_text='Color theme for account (hex code, e.g., #3B82F6)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when account was last updated')),
                ('institution', models.CharField(help_text='Issuing bank or financial institution', max_length=100)),
                ('card_number', encrypted_model_fields.fields.EncryptedCharField(help_text='Full card number (encrypted)')),
                ('card_number_last4', models.CharField(editable=False, help_text='Last 4 digits of card number (for display)', max_length=4)),
                ('cvv', encrypted_model_fields.fields.EncryptedCharField(help_text='Card CVV/CVV2 (encrypted)')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('rupay', 'RuPay'), ('amex', 'American Express')], db_index=True, default='visa', help_text='Type of credit card', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, help_text='Total credit limit on the card', max_digits=18)),
                ('billing_day', models.IntegerField(help_text='Day of month when billing cycle starts (1-31)')),
                ('due_day', models.IntegerField(help_text='Day of month when payment is due (1-31)')),
                ('expiry_date', models.DateField(help_text='Card expiry date (MM/YY)')),
                ('user', models.ForeignKey(help_text='Account owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_cards',
            },
        ),
        migrations.CreateModel(
            name='CreditCardBalance',
            fields=[
                ('account', models.OneToOneField(help_text='Associated credit card', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='creditcards.creditcard')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance (negative = owed, positive = overpayment)', max_digits=18)),
                ('last_posting_id', models.BigIntegerField(blank=True, help_text='ID of last posting that updated this balance', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last balance update')),
            ],
            options={
                'verbose_name': 'Credit Card Balance',
                'verbose_name_plural': 'Credit Card Balances',
                'db_table': 'credit_card_balances',
            },
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['user', 'status'], name='idx_cc_user_status'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['card_type'], name='idx_cc_type'),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('user', 'institution', 'card_number_last4')},
        ),
    ]
