# Generated by Django 5.2.8 on 2025-11-26 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='FD display name/nickname', max_length=100)),
                ('institution', models.CharField(help_text='Bank name', max_length=100)),
                ('fd_number', models.CharField(blank=True, help_text='FD account/certificate number', max_length=50, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Deposited amount', max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('maturity_amount', models.DecimalField(decimal_places=2, help_text='Final amount including interest (user-entered)', max_digits=18)),
                ('compounding_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='quarterly', help_text='Interest compounding frequency', max_length=20)),
                ('tenure_months', models.IntegerField(help_text='Duration in months')),
                ('auto_renewal', models.BooleanField(default=False, help_text='Auto-renew on maturity')),
                ('opened_on', models.DateField(help_text='FD start date')),
                ('maturity_date', models.DateField(help_text='When FD matures')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='FD status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('color', models.CharField(blank=True, help_text='Color code for visual customization (hex format)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('user', models.ForeignKey(help_text='Owner of the FD', on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fixed Deposit',
                'verbose_name_plural': 'Fixed Deposits',
                'db_table': 'fixed_deposits',
                'ordering': ['-maturity_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_fd_user_status'), models.Index(fields=['maturity_date'], name='idx_fd_maturity_date'), models.Index(fields=['status'], name='idx_fd_status')],
            },
        ),
    ]
