# Generated by Django 5.2.8 on 2026-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='tenure_months',
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tenure_days',
            field=models.IntegerField(default=365, help_text='Duration in days'),
        ),
    ]
