# Generated by Django 5.2.8 on 2026-01-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0002_remove_fixeddeposit_tenure_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='tenure_days',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
