# Generated by Django 5.2.8 on 2025-11-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Groceries, Salary)', max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('fee', 'Fee')], db_index=True, help_text='Category type: income, expense, transfer, or fee', max_length=20)),
                ('color', models.CharField(blank=True, help_text='Hex color code for UI visualization (e.g., #3B82F6)', max_length=7, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='System default category (owned by admin)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status (for soft delete/archive)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when category was last updated')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
                ('user', models.ForeignKey(help_text='Owner of the category (admin for defaults)', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_cat_user_active')],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
    ]
