# Generated by Django 5.2.8 on 2025-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Credit Card', 'Credit Card'), ('Digital Wallet', 'Digital Wallet'), ('Cash', 'Cash'), ('Fixed Deposit', 'Fixed Deposit'), ('Loan Account', 'Loan Account')], db_index=True, help_text='Type of account', max_length=20),
        ),
    ]
