# Generated by Django 5.2.8 on 2025-11-22 15:07

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name/nickname for the account', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial balance when account was opened', max_digits=18)),
                ('currency', models.CharField(default='INR', help_text='Currency code (fixed to INR for V1)', max_length=3)),
                ('opened_on', models.DateField(blank=True, help_text='Date when account was opened', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Account status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the account', null=True)),
                ('picture', models.ImageField(blank=True, help_text='Account picture/icon (optional)', null=True, upload_to='account_pictures/')),
                ('color', models.CharField(blank=True, help_text='Color theme for account (hex code, e.g., #3B82F6)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when account was last updated')),
                ('account_type', models.CharField(choices=[('Savings', 'Savings Account'), ('Credit Card', 'Credit Card'), ('Digital Wallet', 'Digital Wallet'), ('Cash', 'Cash'), ('Fixed Deposit', 'Fixed Deposit'), ('Loan Account', 'Loan Account')], db_index=True, help_text='Type of account', max_length=20)),
                ('institution', models.CharField(blank=True, help_text='Bank or financial institution name', max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Branch name', max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code (11 characters)', max_length=11, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='Customer ID with the institution', max_length=50, null=True)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Full account number (encrypted)', null=True)),
                ('account_number_last4', models.CharField(blank=True, editable=False, help_text='Last 4 digits of account number (for display)', max_length=4, null=True)),
                ('user', models.ForeignKey(help_text='Account owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='account',
        ),
        migrations.CreateModel(
            name='BankAccountBalance',
            fields=[
                ('account', models.OneToOneField(help_text='Associated bank account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='accounts.bankaccount')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance (materialized from ledger)', max_digits=18)),
                ('last_posting_id', models.BigIntegerField(blank=True, help_text='ID of last posting that updated this balance', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last balance update')),
            ],
            options={
                'verbose_name': 'Bank Account Balance',
                'verbose_name_plural': 'Bank Account Balances',
                'db_table': 'bank_account_balances',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user', 'status'], name='idx_bank_acc_user_status'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_type'], name='idx_bank_acc_type'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'institution', 'account_number_last4')},
        ),
    ]
