# Generated by Django 5.2.8 on 2025-11-22 15:17

from django.db import migrations, models


def migrate_account_types(apps, schema_editor):
    """
    Convert old capitalized account types to new lowercase values.
    Only migrates bank-related accounts (Savings).
    Other types (Credit Card, Digital Wallet, Cash, Fixed Deposit, Loan Account) 
    will be handled when their respective apps are implemented.
    """
    BankAccount = apps.get_model('accounts', 'BankAccount')
    
    # Mapping from old values to new values
    type_mapping = {
        'Savings': 'savings',
        # Future types - for now, default them to 'savings' temporarily
        # These should be migrated to their respective apps later
        'Credit Card': 'savings',
        'Digital Wallet': 'savings',
        'Cash': 'savings',
        'Fixed Deposit': 'savings',
        'Loan Account': 'savings',
    }
    
    for old_type, new_type in type_mapping.items():
        BankAccount.objects.filter(account_type=old_type).update(account_type=new_type)


def reverse_migrate_account_types(apps, schema_editor):
    """Reverse migration - convert back to old capitalized values"""
    BankAccount = apps.get_model('accounts', 'BankAccount')
    
    # Reverse mapping
    type_mapping = {
        'savings': 'Savings',
        'checking': 'Savings',  # Default to Savings if no exact reverse match
        'current': 'Savings',
        'salary': 'Savings',
    }
    
    for new_type, old_type in type_mapping.items():
        BankAccount.objects.filter(account_type=new_type).update(account_type=old_type)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_remove_accountbalance_account_and_more'),
    ]

    operations = [
        # First, migrate the data while old choices are still valid
        migrations.RunPython(migrate_account_types, reverse_migrate_account_types),
        # Then, update the field definition with new choices
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('current', 'Current Account'), ('salary', 'Salary Account')], db_index=True, default='savings', help_text='Type of bank account', max_length=20),
        ),
    ]
