# Generated by Django 5.2.8 on 2025-12-28 14:53

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_account_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name/nickname for the account', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial balance when account was opened', max_digits=18)),
                ('currency', models.CharField(default='INR', help_text='Currency code (fixed to INR for V1)', max_length=3)),
                ('opened_on', models.DateField(blank=True, help_text='Date when account was opened', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Account status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the account', null=True)),
                ('picture', models.ImageField(blank=True, help_text='Account picture/icon (optional)', null=True, upload_to='account_pictures/')),
                ('color', models.CharField(blank=True, help_text='Color theme for account (hex code, e.g., #3B82F6)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when account was last updated')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('rupay', 'RuPay'), ('amex', 'American Express'), ('other', 'Other')], default='visa', help_text='Type of card', max_length=20)),
                ('card_number', encrypted_model_fields.fields.EncryptedCharField(help_text='Full card number (encrypted)')),
                ('card_number_last4', models.CharField(editable=False, help_text='Last 4 digits of card number (for display)', max_length=4)),
                ('cvv', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Card CVV/CVV2 (encrypted)', null=True)),
                ('expiry_date', models.DateField(help_text='Card expiry date')),
                ('bank_account', models.ForeignKey(help_text='Linked bank account', on_delete=django.db.models.deletion.CASCADE, related_name='debit_cards', to='accounts.bankaccount')),
                ('user', models.ForeignKey(help_text='Account owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debit Card',
                'verbose_name_plural': 'Debit Cards',
                'db_table': 'debit_cards',
                'unique_together': {('user', 'bank_account', 'card_number_last4')},
            },
        ),
    ]
