# Generated by Django 5.2.8 on 2025-11-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ist', models.DateTimeField(db_index=True, help_text='Date and time of transfer (IST)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount (always positive)', max_digits=18)),
                ('from_account_object_id', models.PositiveIntegerField(help_text='ID of source account')),
                ('to_account_object_id', models.PositiveIntegerField(help_text='ID of destination account')),
                ('method_type', models.CharField(choices=[('upi', 'UPI'), ('card', 'Debit/Credit Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash'), ('wallet', 'Digital Wallet'), ('imps_neft_rtgs', 'IMPS/NEFT/RTGS'), ('cheque', 'Cheque'), ('other', 'Other')], db_index=True, help_text='Method used for transfer', max_length=20)),
                ('memo', models.TextField(help_text='Transfer description/notes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('from_account_content_type', models.ForeignKey(help_text='Content type of source account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='contenttypes.contenttype')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Associated journal entry in ledger', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='ledger.journalentry')),
                ('to_account_content_type', models.ForeignKey(help_text='Content type of destination account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Owner of the transfer', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfers',
                'ordering': ['-datetime_ist'],
                'indexes': [models.Index(fields=['user', 'datetime_ist'], name='idx_transfer_user_date'), models.Index(fields=['user', 'deleted_at'], name='idx_transfer_user_deleted')],
            },
        ),
    ]
