# Generated by Django 5.2.8 on 2025-11-23 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_description_category_icon'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ist', models.DateTimeField(db_index=True, help_text='Date and time of transaction (IST)')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (always positive)', max_digits=18)),
                ('account_object_id', models.PositiveIntegerField(help_text='ID of the account')),
                ('method_type', models.CharField(choices=[('upi', 'UPI'), ('card', 'Debit/Credit Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash'), ('wallet', 'Digital Wallet'), ('imps', 'IMPS'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('cheque', 'Cheque'), ('other', 'Other')], db_index=True, help_text='Payment method used', max_length=20)),
                ('purpose', models.TextField(help_text='Description or purpose of transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When transaction was recorded (IST)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (IST)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True)),
                ('account_content_type', models.ForeignKey(help_text='Type of account (BankAccount, CreditCard, etc.)', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('category', models.ForeignKey(help_text='Transaction category', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Linked journal entry in ledger', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='ledger.journalentry')),
                ('user', models.ForeignKey(help_text='Owner of the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-datetime_ist'],
                'indexes': [models.Index(fields=['user', 'datetime_ist'], name='idx_txn_user_time'), models.Index(fields=['user', 'transaction_type'], name='idx_txn_user_type'), models.Index(fields=['category'], name='idx_txn_category'), models.Index(fields=['account_content_type', 'account_object_id'], name='idx_txn_account')],
            },
        ),
    ]
