# Generated by Django 5.2.8 on 2025-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Debit/Credit Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash'), ('wallet', 'Digital Wallet'), ('imps_neft_rtgs', 'IMPS/NEFT/RTGS'), ('cheque', 'Cheque'), ('other', 'Other')], db_index=True, help_text='Payment method used', max_length=20),
        ),
    ]
