# Generated by Django 5.2.8 on 2025-11-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description_category_icon'),
        ('transactions', '0002_alter_transaction_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Transaction category (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category'),
        ),
    ]
