# Generated by Django 5.2.8 on 2025-12-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_debitcard'),
        ('transactions', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debit_card',
            field=models.ForeignKey(blank=True, help_text='Debit card used for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.debitcard'),
        ),
    ]
