# Generated by Django 5.2.8 on 2025-11-23 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('activate', 'Activate')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object')),
                ('object_repr', models.CharField(help_text='String representation of object', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='Field-level changes (for updates) in JSON format', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When action was performed (IST)')),
                ('content_type', models.ForeignKey(help_text='Type of object (Transaction, Account, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_activity_user_time'), models.Index(fields=['content_type', 'object_id'], name='idx_activity_object')],
            },
        ),
    ]
