# Generated by Django 5.2.8 on 2025-11-23 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Control account name', max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('income', 'Income Control'), ('expense', 'Expense Control')], help_text='Type of control account', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Description of this control account')),
            ],
            options={
                'verbose_name': 'Control Account',
                'verbose_name_plural': 'Control Accounts',
                'db_table': 'control_accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the financial event occurred (IST)')),
                ('memo', models.TextField(help_text='Description of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was recorded (IST)')),
                ('user', models.ForeignKey(help_text='Owner of the journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_object_id', models.PositiveIntegerField(help_text='ID of the account')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount (+ for debit, - for credit)', max_digits=18)),
                ('posting_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], db_index=True, help_text='Debit or Credit', max_length=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('memo', models.TextField(blank=True, help_text='Optional posting-specific memo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When posting was created (IST)')),
                ('account_content_type', models.ForeignKey(help_text='Type of account (BankAccount, ControlAccount, etc.)', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('journal_entry', models.ForeignKey(help_text='Parent journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='ledger.journalentry')),
            ],
            options={
                'verbose_name': 'Posting',
                'verbose_name_plural': 'Postings',
                'db_table': 'postings',
                'ordering': ['journal_entry', 'posting_type'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'occurred_at'], name='idx_journal_user_time'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['journal_entry'], name='idx_posting_journal'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['account_content_type', 'account_object_id'], name='idx_posting_account'),
        ),
    ]
